package restpick.entities;
// Generated Aug 30, 2018 4:29:43 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * CalHistory generated by hbm2java
 */
//@Entity
//@Table(name = "cal_history", catalog = "test")
public class CalHistory implements java.io.Serializable {

	
	private Integer id;
	private Integer a;
	private Integer b;
	private Integer sum;

	public CalHistory() {
	}

	public CalHistory(Integer a, Integer b, Integer sum) {
		this.a = a;
		this.b = b;
		this.sum = sum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "a")
	public Integer getA() {
		return this.a;
	}

	public void setA(Integer a) {
		this.a = a;
	}

	@Column(name = "b")
	public Integer getB() {
		return this.b;
	}

	public void setB(Integer b) {
		this.b = b;
	}

	@Column(name = "sum")
	public Integer getSum() {
		return this.sum;
	}

	public void setSum(Integer sum) {
		this.sum = sum;
	}

}
